kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cant-touch-this-pipeline"
spec:
  source:
    git:
      uri: git@github.com/sholly/cant-touch-this.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline