apiVersion: "v1"
kind: Template
objects:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${NAMESPACE}

- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "cant-touch-this-pipeline"
    labels:
      application: ${APPLICATION_NAME}
  spec:
    source:
      git:
        uri: ssh://git@github.com/sholly/cant-touch-this.git
      sourceSecret:
        name: "shollygithub"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
          - name: "BUILD_LOGLEVEL"
            value: "3"
      type: JenkinsPipeline
- apiVersion: "v1"
  kind: "BuildConfig"
  metadata:
    name: "cant-touch-this-pipeline-tag"
    labels:
      application: ${APPLICATION_NAME}
  spec:
    source:
      git:
        uri: ssh://git@github.com/sholly/cant-touch-this.git
      sourceSecret:
        name: "shollygithub"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile.tags
        env:
          - name: "BUILD_LOGLEVEL"
            value: "3"
      type: JenkinsPipeline
- apiVersion: v1
  kind: "BuildConfig"
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: "${NAMESPACE}"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "${IMAGE_STREAM_TAG_NAME}"
          namespace: "${IMAGE_STREAM_NAMESPACE}"
        env:
          - name: "BUILD_LOGLEVEL"
            value: "5"
      type: Source
- apiVersion: v1
  kind: "BuildConfig"
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-quayio
    namespace: "${NAMESPACE}"
  spec:
    output:
      to:
        kind: DockerImage
        name: quay.io/sholly/${APPLICATION_NAME}:latest
      pushSecret:
        name: quayio
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "${IMAGE_STREAM_TAG_NAME}"
          namespace: "${IMAGE_STREAM_NAMESPACE}"
        env:
          - name: "BUILD_LOGLEVEL"
            value: "5"
      type: Source

- apiVersion: v1
  kind: "BuildConfig"
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-quayio-tag
    namespace: "${NAMESPACE}"
  spec:
    output:
      to:
        kind: DockerImage
        name: quay.io/sholly/${APPLICATION_NAME}:${BUILD_TAG}
      pushSecret:
        name: quayio
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: "${IMAGE_STREAM_TAG_NAME}"
          namespace: "${IMAGE_STREAM_NAMESPACE}"
        env:
          - name: "BUILD_LOGLEVEL"
            value: "5"

- apiVersion: v1
  kind: Secret
  data:
    ssh-privatekey: ${SSH_PRIVATE_KEY}
  metadata:
    labels:
      application: ${APPLICATION_NAME}
      credential.sync.jenkins.openshift.io: 'true'
    name: ${SSH_KEY_NAME}
    namespace: ci-cd
  type: kubernetes.io/ssh-auth
parameters:
- description: Application Name
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: cant-touch-this
- description: Namespace
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: 
- description: ssh key name
  displayName: ssh key name
  name: SSH_KEY_NAME
  required: true
  value: 
- description: ssh private key value
  displayName: ssh private key
  name: SSH_PRIVATE_KEY
  required: true
  value: 
- description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  required: true
  value: openshift
- description: Image stream tag for the image you'd like to use to build the application
  name: IMAGE_STREAM_TAG_NAME
  required: true
  value: redhat-openjdk18-openshift:1.5
- description: Quay build tag
  name: BUILD_TAG
  required: true
  value: devrc
