kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cant-touch-this-pipeline"
spec:
  source:
    git:
      uri: https://github.com/sholly/cant-touch-this.git
    sourceSecret:
      name: "cant-touch-this"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline